version: '3'

services:
    # Application service
  app:
    build: .
    env_file:
      - .env.prod
    volumes:
      - app_static:/app/static

  database:
    # Database service
    image: postgres:latest
    env_file:
      - .env.prod
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webserver:
    # Web server service
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - app_static:/var/www/static
    depends_on:
      - app

volumes:
  app_static:
  database_data:
